/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as FinancienRouteImport } from './routes/financien'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as ContractenRouteImport } from './routes/contracten'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MTokenRouteImport } from './routes/m.$token'
import { Route as InvoiceIdRouteImport } from './routes/invoice.$id'
import { Route as ApiN8nChatRouteImport } from './routes/api/n8n-chat'
import { Route as ScanDesktopTokenRouteImport } from './routes/scan.desktop.$token'
import { Route as ApiPublicHooksSyncGmailRouteImport } from './routes/api/public/hooks/sync-gmail'
import { Route as ApiPublicHooksEcosystemEventRouteImport } from './routes/api/public/hooks/ecosystem-event'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancienRoute = FinancienRouteImport.update({
  id: '/financien',
  path: '/financien',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractenRoute = ContractenRouteImport.update({
  id: '/contracten',
  path: '/contracten',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MTokenRoute = MTokenRouteImport.update({
  id: '/m/$token',
  path: '/m/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN8nChatRoute = ApiN8nChatRouteImport.update({
  id: '/api/n8n-chat',
  path: '/api/n8n-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanDesktopTokenRoute = ScanDesktopTokenRouteImport.update({
  id: '/desktop/$token',
  path: '/desktop/$token',
  getParentRoute: () => ScanRoute,
} as any)
const ApiPublicHooksSyncGmailRoute = ApiPublicHooksSyncGmailRouteImport.update({
  id: '/api/public/hooks/sync-gmail',
  path: '/api/public/hooks/sync-gmail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEcosystemEventRoute =
  ApiPublicHooksEcosystemEventRouteImport.update({
    id: '/api/public/hooks/ecosystem-event',
    path: '/api/public/hooks/ecosystem-event',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/contracten': typeof ContractenRoute
  '/ecosystem': typeof EcosystemRoute
  '/financien': typeof FinancienRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/scan': typeof ScanRouteWithChildren
  '/api/n8n-chat': typeof ApiN8nChatRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/m/$token': typeof MTokenRoute
  '/scan/desktop/$token': typeof ScanDesktopTokenRoute
  '/api/public/hooks/ecosystem-event': typeof ApiPublicHooksEcosystemEventRoute
  '/api/public/hooks/sync-gmail': typeof ApiPublicHooksSyncGmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/contracten': typeof ContractenRoute
  '/ecosystem': typeof EcosystemRoute
  '/financien': typeof FinancienRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/scan': typeof ScanRouteWithChildren
  '/api/n8n-chat': typeof ApiN8nChatRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/m/$token': typeof MTokenRoute
  '/scan/desktop/$token': typeof ScanDesktopTokenRoute
  '/api/public/hooks/ecosystem-event': typeof ApiPublicHooksEcosystemEventRoute
  '/api/public/hooks/sync-gmail': typeof ApiPublicHooksSyncGmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/contracten': typeof ContractenRoute
  '/ecosystem': typeof EcosystemRoute
  '/financien': typeof FinancienRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/scan': typeof ScanRouteWithChildren
  '/api/n8n-chat': typeof ApiN8nChatRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/m/$token': typeof MTokenRoute
  '/scan/desktop/$token': typeof ScanDesktopTokenRoute
  '/api/public/hooks/ecosystem-event': typeof ApiPublicHooksEcosystemEventRoute
  '/api/public/hooks/sync-gmail': typeof ApiPublicHooksSyncGmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/contracten'
    | '/ecosystem'
    | '/financien'
    | '/inbox'
    | '/login'
    | '/scan'
    | '/api/n8n-chat'
    | '/invoice/$id'
    | '/m/$token'
    | '/scan/desktop/$token'
    | '/api/public/hooks/ecosystem-event'
    | '/api/public/hooks/sync-gmail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/contracten'
    | '/ecosystem'
    | '/financien'
    | '/inbox'
    | '/login'
    | '/scan'
    | '/api/n8n-chat'
    | '/invoice/$id'
    | '/m/$token'
    | '/scan/desktop/$token'
    | '/api/public/hooks/ecosystem-event'
    | '/api/public/hooks/sync-gmail'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/contracten'
    | '/ecosystem'
    | '/financien'
    | '/inbox'
    | '/login'
    | '/scan'
    | '/api/n8n-chat'
    | '/invoice/$id'
    | '/m/$token'
    | '/scan/desktop/$token'
    | '/api/public/hooks/ecosystem-event'
    | '/api/public/hooks/sync-gmail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  ContractenRoute: typeof ContractenRoute
  EcosystemRoute: typeof EcosystemRoute
  FinancienRoute: typeof FinancienRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  ScanRoute: typeof ScanRouteWithChildren
  ApiN8nChatRoute: typeof ApiN8nChatRoute
  InvoiceIdRoute: typeof InvoiceIdRoute
  MTokenRoute: typeof MTokenRoute
  ApiPublicHooksEcosystemEventRoute: typeof ApiPublicHooksEcosystemEventRoute
  ApiPublicHooksSyncGmailRoute: typeof ApiPublicHooksSyncGmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financien': {
      id: '/financien'
      path: '/financien'
      fullPath: '/financien'
      preLoaderRoute: typeof FinancienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracten': {
      id: '/contracten'
      path: '/contracten'
      fullPath: '/contracten'
      preLoaderRoute: typeof ContractenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$token': {
      id: '/m/$token'
      path: '/m/$token'
      fullPath: '/m/$token'
      preLoaderRoute: typeof MTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n8n-chat': {
      id: '/api/n8n-chat'
      path: '/api/n8n-chat'
      fullPath: '/api/n8n-chat'
      preLoaderRoute: typeof ApiN8nChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/desktop/$token': {
      id: '/scan/desktop/$token'
      path: '/desktop/$token'
      fullPath: '/scan/desktop/$token'
      preLoaderRoute: typeof ScanDesktopTokenRouteImport
      parentRoute: typeof ScanRoute
    }
    '/api/public/hooks/sync-gmail': {
      id: '/api/public/hooks/sync-gmail'
      path: '/api/public/hooks/sync-gmail'
      fullPath: '/api/public/hooks/sync-gmail'
      preLoaderRoute: typeof ApiPublicHooksSyncGmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ecosystem-event': {
      id: '/api/public/hooks/ecosystem-event'
      path: '/api/public/hooks/ecosystem-event'
      fullPath: '/api/public/hooks/ecosystem-event'
      preLoaderRoute: typeof ApiPublicHooksEcosystemEventRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ScanRouteChildren {
  ScanDesktopTokenRoute: typeof ScanDesktopTokenRoute
}

const ScanRouteChildren: ScanRouteChildren = {
  ScanDesktopTokenRoute: ScanDesktopTokenRoute,
}

const ScanRouteWithChildren = ScanRoute._addFileChildren(ScanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  ContractenRoute: ContractenRoute,
  EcosystemRoute: EcosystemRoute,
  FinancienRoute: FinancienRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  ScanRoute: ScanRouteWithChildren,
  ApiN8nChatRoute: ApiN8nChatRoute,
  InvoiceIdRoute: InvoiceIdRoute,
  MTokenRoute: MTokenRoute,
  ApiPublicHooksEcosystemEventRoute: ApiPublicHooksEcosystemEventRoute,
  ApiPublicHooksSyncGmailRoute: ApiPublicHooksSyncGmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
